package V5TajweedFactoryOnto;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu Jul 09 05:14:12 PKT 2020 by Ramsha
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Ghunnah
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GHUNNAH.<p>
     * 
     */
    public static final OWLClass CLASS_GHUNNAH = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Ghunnah"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Hamzatulwasal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAMZATULWASAL.<p>
     * 
     */
    public static final OWLClass CLASS_HAMZATULWASAL = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Hamzatulwasal"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Harakat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HARAKAT.<p>
     * 
     */
    public static final OWLClass CLASS_HARAKAT = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Harakat"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IdghaamShafawiLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMSHAFAWILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMSHAFAWILETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IdghaamShafawiLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IdghaamWithGhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMWITHGHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMWITHGHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IdghaamWithGhunnahLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IdghaamWithoutGhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMWITHOUTGHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMWITHOUTGHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IdghaamWithoutGhunnahLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IkhfaLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IKHFALETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IKHFALETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IkhfaLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IkhfaShafawiLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IKHFASHAFAWILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IKHFASHAFAWILETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IkhfaShafawiLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IqlabLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IQLABLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IQLABLETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IqlabLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Item
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ITEM.<p>
     * 
     */
    public static final OWLClass CLASS_ITEM = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Item"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IzharLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IZHARLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IZHARLETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IzharLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#IzharShafawiLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IZHARSHAFAWILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IZHARSHAFAWILETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#IzharShafawiLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Letter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LETTER.<p>
     * 
     */
    public static final OWLClass CLASS_LETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Letter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#LetterOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LETTEROCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_LETTEROCCURRENCE = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#LetterOccurrence"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#MaadLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAADLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_MAADLETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#MaadLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#MeemSakinah
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEEMSAKINAH.<p>
     * 
     */
    public static final OWLClass CLASS_MEEMSAKINAH = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#MeemSakinah"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#NoonSakinahAndTanween
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOONSAKINAHANDTANWEEN.<p>
     * 
     */
    public static final OWLClass CLASS_NOONSAKINAHANDTANWEEN = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#NoonSakinahAndTanween"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Qalqalah
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QALQALAH.<p>
     * 
     */
    public static final OWLClass CLASS_QALQALAH = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Qalqalah"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#QalqalahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QALQALAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_QALQALAHLETTER = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#QalqalahLetter"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#RuleOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RULEOCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_RULEOCCURRENCE = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#RuleOccurrence"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Rules
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RULES.<p>
     * 
     */
    public static final OWLClass CLASS_RULES = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Rules"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Tanween
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TANWEEN.<p>
     * 
     */
    public static final OWLClass CLASS_TANWEEN = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Tanween"));

    /* ***************************************************
     * Class http://www.tajweedontology.org/ontologies/rules#Word
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WORD.<p>
     * 
     */
    public static final OWLClass CLASS_WORD = factory.getOWLClass(IRI.create("http://www.tajweedontology.org/ontologies/rules#Word"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#composeWord
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPOSEWORD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPOSEWORD = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#composeWord"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#containLetter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINLETTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINLETTER = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#containLetter"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#followedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOLLOWEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOLLOWEDBY = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#followedBy"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#hasRuleOccurrence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRULEOCCURRENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRULEOCCURRENCE = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#hasRuleOccurrence"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#hasRuleType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRULETYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRULETYPE = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#hasRuleType"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#involveHarakat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVEHARAKAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVEHARAKAT = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#involveHarakat"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#involveLetter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVELETTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVELETTER = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#involveLetter"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#occurAt
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OCCURAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OCCURAT = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#occurAt"));

    /* ***************************************************
     * Object Property http://www.tajweedontology.org/ontologies/rules#precededBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRECEDEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRECEDEDBY = factory.getOWLObjectProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#precededBy"));

    /* ***************************************************
     * Data Property http://www.tajweedontology.org/ontologies/rules#hasHaraktPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASHARAKTPOSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASHARAKTPOSITION = factory.getOWLDataProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#hasHaraktPosition"));

    /* ***************************************************
     * Data Property http://www.tajweedontology.org/ontologies/rules#hasLetterPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLETTERPOSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLETTERPOSITION = factory.getOWLDataProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#hasLetterPosition"));

    /* ***************************************************
     * Data Property http://www.tajweedontology.org/ontologies/rules#involveSurahNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INVOLVESURAHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INVOLVESURAHNO = factory.getOWLDataProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#involveSurahNo"));

    /* ***************************************************
     * Data Property http://www.tajweedontology.org/ontologies/rules#involveVerseNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INVOLVEVERSENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INVOLVEVERSENO = factory.getOWLDataProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#involveVerseNo"));

    /* ***************************************************
     * Data Property http://www.tajweedontology.org/ontologies/rules#involveWord
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INVOLVEWORD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INVOLVEWORD = factory.getOWLDataProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#involveWord"));

    /* ***************************************************
     * Data Property http://www.tajweedontology.org/ontologies/rules#involveWordNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INVOLVEWORDNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INVOLVEWORDNO = factory.getOWLDataProperty(IRI.create("http://www.tajweedontology.org/ontologies/rules#involveWordNo"));


}
